package main;

import javax.swing.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class MePanel extends JPanel {

    /**
     * Creates new form empPanel
     */
    public MePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold default-state="collapsed" desc="Generated Code">
    private void initComponents() {

        nameLabel = new JLabel();
        passUpdateLabel = new JLabel();
        userUpdateLabel = new JLabel();

        nameLabel.setFont(new java.awt.Font("Liberation Sans", 0, 34));
        nameLabel.setText("Yeabsira Yonas");

        passUpdateLabel.setIcon(new ImageIcon("src/main/icons/passUpdate.png"));
        userUpdateLabel.setIcon(new ImageIcon("src/main/icons/userUpdate.png"));

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(406, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(userUpdateLabel, GroupLayout.PREFERRED_SIZE, 282, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(passUpdateLabel, GroupLayout.PREFERRED_SIZE, 281, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nameLabel, GroupLayout.PREFERRED_SIZE, 229, GroupLayout.PREFERRED_SIZE))
                                .addGap(314, 314, 314))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(nameLabel, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE)
                                .addGap(159, 159, 159)
                                .addComponent(userUpdateLabel)
                                .addGap(54, 54, 54)
                                .addComponent(passUpdateLabel)
                                .addContainerGap(256, Short.MAX_VALUE))
        );

        userUpdateLabel.addMouseListener(myMouseAdapter(userUpdateLabel,"src/main/icons/userUpdate"));
        passUpdateLabel.addMouseListener(myMouseAdapter(passUpdateLabel,"src/main/icons/passUpdate"));
    }// </editor-fold>

    private MouseAdapter myMouseAdapter(JLabel label,String file){
        return new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                label.setIcon(new ImageIcon(file + "2.png"));
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                label.setIcon(new ImageIcon(file + ".png"));
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                label.setIcon(new ImageIcon(file + "2.png"));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                label.setIcon(new ImageIcon(file + ".png"));
            }
        };
    }

    // Variables declaration - do not modify
    private JLabel nameLabel;
    private JLabel passUpdateLabel;
    private JLabel userUpdateLabel;
    // End of variables declaration
}
